### ISSUE TITLE
关于连接的问题

### ISSUE THREAD

**Issue by hzka** [452MJ/BLE-RSSI-Sample#2]
你好，麻烦问下两个设备如何连接的？被连接的设备只能是蓝牙发送器么？是通过蓝牙匹配之后再行操作？我采用的是两个手机蓝牙连接匹配之后，不知道为什么不显示连接设备。
谢谢！

**Comment by hzka** [comment]
解决了，是因为没有赋予他.ACCESS_COARSE_LOCATION，.ACCESS_FINE_LOCATION权限
 <uses-permission android:name="android.permission.ACCESS_COARSE_LOCATION"/>
    <uses-permission android:name="android.permission.ACCESS_FINE_LOCATION"/>
这两个权限。还有这个是不是阉割之后的呀，没有您图二展示的设置这一个选项。。。

**Comment by 452MJ** [comment]
@hzka 对，设置那一页忘记上传了，代码在角落的笔记本😂。其实就是一个页面用于保存报警db到SharedPreference而已

**Comment by hzka** [comment]
谢谢大佬回复，大概理解这部分的实现过程，因为刚接触，所以还有一点不大明白：就是他这个设备地址是对方的蓝牙地址么？搜索到的一些地址和测试的蓝牙地址不一样，好像并没有搜索到蓝牙地址。。烦请解答。谢谢。

**Comment by 452MJ** [comment]
@hzka 那个好像是设备的MAC物理地址，不是ip地址
